### ISSUE TITLE
Deploy OpenStack Control and 3 Client nodes via Chef in Packet

### ISSUE THREAD

**Issue by robertstarmer** [cncf/cnfs#100]
- [x] Deploy packet nodes manually for control and client nodes
- [x] Launch Chef driven OpenStack services on control node (non-ha)
- [x] Launch Chef drive OpenStack client nodes (3 replicas)
- [x] Verify all network functions:
-- [ ] VM access to upstream (public service)
-- [ ] Access to VMs from upstream (via floating IP)
-- [ ] VM-VM access
- [x] Document process for delivering running system

**Comment by lixuna** [comment]
What's left: 

- document and verify network functions
- document process for delivering system
- commit to folder
- tag issues in commits, by adding ‘[#100]’ to the first message to link to issue #100

**Comment by taylor** [comment]
Primary docs for deploy in https://github.com/cncf/cnfs/blob/master/comparison/chained_nf_test/openstack/deploy_openstack/README.md
