### ISSUE TITLE
Invite Ed Kern to CNFs GitHub repo and CNCF slack channels

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#106]
Action item: onboard Ed Kern to CNF project
---

Requested via email by M.Konstantynowicz

Requested on Mon, Oct 29, 3:35 PM

Tasks:
---

- [x]  add “snergster” to https://github.com/cncf/cnfs
- [x] Ed accept invite

- [x]  send an invitation for cloud-native.slack.com to Ed K. 

- [x] Invite to CNCF Packet.net org
- [x] Ed accept invite
- [x] Add to CNCF CNF project on Packet.net

> Thank you in advance for your help with the VNF vs. CNF Comparison project.
> 
> Please join the cncf.io slack by visiting https://slack.cncf.io and entering your email address. You'll receive an invite and a link to create an account. After you have created your account on https://cloud-native.slack.com, please find and join the #cnf and dev-cnf-kubecon channels.
> 
> There are many Slack apps available for Linux, Windows, Mac, iPhone, Android and you can also use the web browser. 

- [x]  add Ed Kern to #cnf and dev-cnf-kubecon channels on slack

**Comment by lixuna** [comment]
Taylor Carpenter [18 hours ago]

- Packet.net invite will be sent by @Taylor Waggoner to ejk@cisco.com


Taylor Carpenter [17 hours ago]

- Ed has been invited to the packet project.
- Github invite can be accepted at https://github.com/cncf/cnfs/invitations

**Comment by lixuna** [comment]
<img width="432" alt="screenshot 2018-10-30 12 16 25" src="https://user-images.githubusercontent.com/11701267/47736900-b0ac5580-dc3d-11e8-800e-861ac7116599.png">

**Comment by Snergster** [comment]
took a few hours for packet to unjam my packet.net account (cisco.com wasn't my primary with them but its all good now)   so the only thing i see above that I cannot figure out is how to join
dev-cnf-kubecon channel
