### ISSUE TITLE
Create ansible code to setup Packet.net Mixed Layer-2 / Layer-3 network

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#113]
Reference issue #90 

Tasks:
- [x] Test and validate Packet.net api code
- [x] add support for more devices
- [x] add support for instance id
- [x] Get api code working in tool container
- [x] Create roles for running API code tasks
   * [x] create vlan
   * [x] disbond interface from packet bond
   * [x] assign vlan to port on server
   * [x] destroy vlan
   * [x] add interface to packet bond
   * [x] unassign vlan from port on server

- [x] Create playbook for creating Mixed Packet.net network
- [x] Update Packet Generator provisioning to use new Packet API code

Related issues/tasks:
-  Create top level playbook for the test case #107

----

Setting up layer-2 for a server via Packet.net API
1. Create vlan
2. Disbond interface from default bond
3. Assign vlan to disbonded interface

**Comment by lixuna** [comment]
Level of effort in pts: 1, 2, 3, 5, 8, 13, 21 => 3 pts
---

**Comment by taylor** [comment]
Setting up layer-2 for a server via Packet.net API

1. Create vlan
    `. .env ; ruby l2_packet_networking.rb --create-vlan vlantest27 --project-name='CNCF CNFs' --packet-url='api.packet.net' --facility='ewr1'`
2. Disbond interface from default bond
    `. .env ; ruby l2_packet_networking.rb --server 'quadtestb-07' --disbond-interface eth3 --project-name='CNCF CNFs' --packet-url='api.packet.net'`
3. Assign vlan to disbonded interface
    `. .env ; ruby l2_packet_networking.rb --server 'quadtestb-07' --assign-vlan quadtestvlan1 --assign-vlan-port eth3 --project-name='CNCF CNFs' --packet-url='api.packet.net' --facility='ewr1'`

**Comment by taylor** [comment]
Need to get code working in [tool container](https://github.com/cncf/cnfs/blob/master/tools/deploy/Dockerfile)
