### ISSUE TITLE
System specs for the Packet machines used in the Kubecon Seattle comparison

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#117]
This provides details on the machines used in the K8s and OpenStack clusters as well as those used for generating traffic.

- [x] Add high-level specs for k8s worker nodes and openstack compute nodes
- [x] Add high-level specs for traffic generator machine
- [x] Add BIOS information for the machines running dataplane NFs
- [x] Add detailed machine specs for worker/compute nodes

**Comment by taylor** [comment]
Additional NIC information https://github.com/cncf/cnfs/issues/94

**Comment by taylor** [comment]
@michaelspedersen, @pmikus, @mackonstan this ticket will contain the specs for the systems being used at Packet for the Kubecon comparison test case.

**Comment by michaelspedersen** [comment]
> keep 1/socket for host / kernel
> that leaves you 2x13 cores to play with, between VPP and NFs

This has also been my go-to approach for configuration so far. We've been trying out a few different configurations (scaling both VPP and VNFs/CNFs)

**Comment by ahothan** [comment]
in general it would be reasonable to find the "best performing system" given the same amount of resources and preferably in conditions that are realistic and close to production conditions.

**Comment by taylor** [comment]
BIOS details are in #129
