### ISSUE TITLE
Setup access to the Packet CNCF CNF test systems via SSH

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#118]
Tasks: 
---

Week of Nov 5th, 2018
- [x] provide public SSH key
  - [x] @pmikus 
  - [x] @Snergster 
  - [x] @ahothan 
  - [x] @mackonstan 

- [x] @taylor add public SSH keys to Packet machines
  - [x] @pmikus 
  - [x] @Snergster 
  - [x] @ahothan 
  - [x] @mackonstan 

- [x] verify access to Packet machine
  - [x] @pmikus 
  - [x] @Snergster 
  - [x] @ahothan 
  - [x] @mackonstan 
---

**Comment by Snergster** [comment]
https://github.com/Snergster.keys

**Comment by ahothan** [comment]
pls add my pub keys as well:
https://github.com/ahothan.keys

**Comment by pmikus** [comment]
https://github.com/pmikus.keys

**Comment by mackonstan** [comment]
How did you do mention on github?
Can you point me to the file, so I can
See ascii characters?
Cheers,
-Maciek

**Comment by taylor** [comment]
@Snergster, @pmikus, @ahothan your keys have been added to the project as well as directly to some of the test servers that are currently running.  See Slack for machine info.

@mackonstan, please provide a link to your public ssh key or add it directly as a comment here.

hmm, github mentions use @ + username.  Eg. @mackonstan.  Lots of good info in the "github help" docs (with good matches in google search) -- https://help.github.com/articles/mentions-on-github-pages/

**Comment by mackonstan** [comment]
@taylor how do we access packet.net machines allocated to us? page with instructions?
