### ISSUE TITLE
Perform multi-chaining tests on Packet.net and compare with CSIT test results

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#127]
- [x] Clone the code changes from `baseline_nf_performance-csit` to `baseline_nf_performance-packet`
  - [x] Align `packet_generator` deployment scripts
    - [x] Ansible, configs
    - [x] Manual scripts, configs
  - [x] Align `cnf_edge_router` deployment scripts
    - [x] Manual scripts, configs
  - [x] Align `vEdge` deployment scripts
    - [x] Manual scripts, configs
  - [x] Extensive testing of deployment.
- [x] Fix the VLAN assignment questions (quad1-2). How many are available?
- [x] Provide data for single_chain.
- [x] Compare data for single chain.
- [x] Provide data for multiple_chains.
- [x] Compare data for multiple_chainschain.

**Comment by taylor** [comment]
Blocker with VLAN not showing on port 3. 

@pmikus the vlan issue should be resolved in #137

**Comment by pmikus** [comment]
From within directory of results:
64B
$ jq -r '.benchmarks.network.service_chain.EXT.result.result."64".run_config."direction-total".rx  | "64B \(.rate_pps)pps (\(.rate_bps)bps) " + input_filename' *pps*.json
IMIX
$ jq -r '.benchmarks.network.service_chain.EXT.result.result.IMIX.run_config."direction-total".rx  | "IMIX \(.rate_pps)pps (\(.rate_bps)bps) " + input_filename' *pps*.json
