### ISSUE TITLE
Update NUMA configuration in grub kernel options

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#131]
Reference
* [BIOS settings issue 129](https://github.com/cncf/cnfs/issues/129)
* [NUMA Best Practices for Dell PowerEdge
12th Generation Servers](http://doc.xueqiu.com/14738e1820f33fea1ba083fd.pdf)

- [ ] Determine settings that need to be updated
- [ ] Determine best kernel isolcpu setting

**Comment by taylor** [comment]
@pmikus found that the m2.xlarge.x86 instances have 
```
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55
```
Currently grub has `isolcpu=2-27` which covers only half of the cores.  The second half (specifically HTT cores) are not isolated.  

Suggested change is `isolcpu=2-27,30-55` to cover all cores.

**Comment by michaelspedersen** [comment]
@taylor the 2-27 matches what I've done on the machines I've been working on (quad3-4). Those were with HT disabled. I agree with your proposed change if 28-29 are indeed the two threads on core 0 on socket 1 (which I **assume** they are)

**Comment by pmikus** [comment]
Quad9 recommended:
isolcpu=2-27,30-55, rcu_nocbs=2-27,30-55 nohz_full=2-27,30-55 nmi_watchdog=0 audit=0 nosoftlockup processor.max_cstate=1 intel_idle.max_cstate=1 hpet=disable tsc=reliable mce=off  numa_balancing=disable intel_pstate=disable intel_iommu=on iommu=pt
Quad1-4 to be same.

**Comment by pmikus** [comment]
> 
> 
> @taylor the 2-27 matches what I've done on the machines I've been working on (quad3-4). Those were with HT disabled. I agree with your proposed change if 28-29 are indeed the two threads on core 0 on socket 1 (which I **assume** they are)

GRUB can be used for HT no matter if HT is enabled.
