### ISSUE TITLE
Create README for KubeCon keynote comparison

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#134]
## Create README for KubeCon keynote comparison

- [x] Create https://github.com/cncf/cnfs/tree/master/comparison/kubecon18-chained_nf_test/README.md
- [x] Short description (one line: ie “Comparing performance of NFs on OpenStack and K8s”)
- [ ] Add an aspirational message of test bed (ie. Ideally, you'll only need an API key from Packet/bare metal to deploy and replicate results. Currently, some customization is needed on machines and BIOS configuration, etc.)
- [ ] What is this test comparison? (Add a description of test comparison)
- [ ] Where are we right now? (compared to aspiration)

- [x] Document the requirements for the workstation that does the deployment and runs the tests
- [ ] Describe the K8s and OpenStack testbed 
   - [ ] Add information about systems being tested
      *  See https://github.com/cncf/cnfs/issues/117
   - [x] Add wiring diagrams showing machines, switches and layer-2 network
- [ ] Describe the test cases (eg. snake and pipeline) 
   * add high-level diagram or link to another document.  See https://github.com/cncf/cnfs/issues/155
- [ ] Test results
    * [ ] Add summary of test results
    * [ ] Add links to more extensive results or nfvbench logs

### Steps to recreate test results

Add steps to recreate test results, including manual steps for configuring reserved instances and BIOS tasks

Common
- [ ] Packet account
- [ ] Pre-req software to install

*Reserved instances*
- [ ] BIOS customizations
- [ ] Hardware setup information

TBD

*On-Demand instances*

TBD

**Comment by taylor** [comment]
Audience: Person who wants to recreate the results themselves on Packet

High level requirements
- Packet: account, Project ID, API key, SSH key
- End-user workstation: ssh, git, docker

**Comment by denverwilliams** [comment]
Steps for the Packet Generator
'./kubecon18-chained_nf_test/packet_generator/deploy_packet_generator.sh'

**Comment by taylor** [comment]
We can create additional steps for the quad intel x710 machines.

**Comment by taylor** [comment]
Add a prominent notice that the end-user is responsible for all Packet charges and updates in the project chosen.  (eg. instances deleted or left around)

**Comment by michaelspedersen** [comment]
Images showing the configuration from an end-user perspective (no mention of internal configuration, i.e. MACs or L3)

### Logical L2
![logical_l2](https://user-images.githubusercontent.com/40474606/48738318-dd84d480-ec0d-11e8-90b2-b3dbfbd3096b.png)

### Physical L2
![phys_l2](https://user-images.githubusercontent.com/40474606/48738319-dd84d480-ec0d-11e8-8078-89240e41eeb0.png)

**Comment by taylor** [comment]
Packet systems specs are in https://github.com/cncf/cnfs/issues/117#issuecomment-436271074

**Comment by michaelspedersen** [comment]
Adding network overview of different setups here too:

![network_overview](https://user-images.githubusercontent.com/40474606/48859161-9536f500-ed7a-11e8-88a9-627d2b3c79ec.png)

**Comment by Snergster** [comment]
updated readme adding in details and leaving large markers for what is still unknown (or just not known by me)

**Comment by lixuna** [comment]
Closing, will resume updates to README in #166
