### ISSUE TITLE
Update CNF Kubecon Keynote (high-level) slide deck

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#142]
## Update CNF Kubecon Keynote slides

Tasks:
- [x] Add slide to explain CNF project goals for the Kubecon keynote comparison
 - [x] Add High level description of CNF project
- [x]   Add a slide to describe what network functions are doing in the test case
- [x] Add slides to describe the test bed used for the comparison
   * eg. Where is done?  => Packet, What systems are used? 
- [x]  Be consistent with wording (use Cloud-Native Network Functions for CNF) 
- [x] Re-order the slides to show VNFs slide before CNFs slide 
- [x] Remove the word "pod" from CNF slides
- [x] Remove the word "VM" from VNF slides
- [x] Add slide to describe current test case 
   * [x] Create visualization of the single chain snake case
   * [x] Create visualization of the single chain best case
   * [x] Write up description of  single chain snake test case
   * [x] Write up description of  single  chain best case

   * [x] Create visualization of the multichain snake test case (apples-to-apples)
   * [x] Create visualization of the multichain best test case 
   * [x] Write up description of multichain snake test case
   * [x] Write up description of multichain best test case
  - [x]  Add a slides that go over density  => multichain test cases cover this
   * A multichain test case is one example of high density on a worker node
   * [x] Create write up of the density idea
- [x]  Add a slide to show performance results
- [x]  Add a slide to explain next phase of testbed
- [x]  Update speaker notes to be consistent/updated

**Comment by taylor** [comment]
Write up of the density idea
- Apples to apples higher density
- If possible, highlight / demonstrate how lower resource usage of CNFs gives higher performance.
  Ex. "Demonstrate how lower memory usage is given higher throughput"

**Comment by taylor** [comment]
*Add a slides to show that show density idea*

Draft/WIP of multiple options to visualize the multichain test case

**Comment by lixuna** [comment]
To Dos: 
---

- [ ] Add High level description of CNF project

- [ ] Add a slide to describe what network functions are doing in the test case
