### ISSUE TITLE
KubeCon Seattle CNF project registration logistics

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#144]
Short description: 
- register Peter M and Damjan M to KubeCon Seattle

Tasks: 
- [x] transfer registration to Damjan M
- [x] transfer registration to Peter M

- [x] send followup via email to confirm transfer to Damjan M
- [x] send followup via email to confirm transfer to Peter M

Acceptance Criteria:
- [ ] Damjan M to confirm successful transfer
  - [ ]  email received from CNCF Events Team re: "KubeCon + CloudNativeCon 2018 Registration Confirmation"
- [ ] Peter M to confirm successful transfer
  - [ ]  email received from CNCF Events Team re: "KubeCon + CloudNativeCon 2018 Registration Confirmation"

**Comment by lixuna** [comment]
@pmikus please confirm that an email from CNCF Events Team re: "KubeCon + CloudNativeCon 2018 Registration Confirmation" has been sent to your email address

**Comment by lixuna** [comment]
@dmarion please confirm that an email from CNCF Events Team re: "KubeCon + CloudNativeCon 2018 Registration Confirmation" has been sent to your email address

**Comment by taylor** [comment]
Verbal confirmation
