### ISSUE TITLE
Add support for a OpenStack VNF to be isolated to CPU socket 0 / single NUMA zone

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#147]
Add support for a VNF to be isolated to CPU socket 0 / single NUMA zone.
---

Short Description: 
- The VM running on OpenStack should use only CPU socket 0 so it is isolated to a single NUMA zone.  The socket used should be configurable outside of the VM

Tasks: 
---

- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by robertstarmer** [comment]
These parameters:
--property hw:numa_nodes=0 --property hw:mem_page_size=2048

Can be added to a node creation, or can be added to a flavor. If they're added to a flavor, using the openstack client:

```
openstack flavor create --id 2 --ram 32768 --disk 10 --property hw:numa_nodes=0 --property hw:mem_page_size=2048 hp.large
```

Or as a server create command:
```
openstack  server create test${1} --flavor 1 --image xenial --nic net-id=${network} --property hw:numa_nodes=0 --property hw:mem_page_size=2048
```
