### ISSUE TITLE
Add support for using Ubuntu 16.04 as the host OS for OpenStack compute nodes

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#156]
- [x] Support deploying OpenStack compute nodes to an Ubuntu 16.04 Host
- [x] Setup Ubuntu unbond and vlan mapping
- [x] Support OVS networking (See #150) 
- [x] Add automation to fix vncproxy configuration
- [x] script to set up default security groups (ping, ssh, icmp)
- [x]  add reboot after ovs resource install
- [x] dashboard install /var/lib/openstack-dashboard/secret_key file ends up with the wrong permissions

**Comment by robertstarmer** [comment]
-[ ] Add automation to fix vncproxy configuration

**Comment by robertstarmer** [comment]
- [ ] script to set up default security groups (ping, ssh, icmp)
- [ ] add reboot after ovs resource install

**Comment by robertstarmer** [comment]
This is done and committed as a part of the Issue #101 fixes.
