### ISSUE TITLE
[KubeCon18] Benchmark 3 Service Densities of the Snake test case on KVM

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#157]
Run benchmark tests and add the results to this ticket.  All tests will be run against a machine running KVM.

Use the same number of cores and threads which are used for the K8s benchmark tests. See #159 

- [x] Document KVM snake test case in this ticket

*Quad Intel Snake Test*
- [x] Deploy KVM system on a quad intel m2.xlarge Packet system
- [x] Setup VPP vSwitch similar to K8s worker node
- [ ] Deploy VNFs to KVM in snake test cases:
  - [ ] KVM Intel Snake (VSC)
      - [ ] 3 Chains, 1 NF
      - [ ] 3 Chains, 2 NFs
      - [x] 2 Chains, 3 NFs
- [x] Run nfvbench against KVM system for each service density and test case above
- [ ] Collect results and save logs to this ticket
- [ ] Summarize results, including a single throughput number
- [ ] Add system resource information, including memory and cpu usage by VNFs and KVM to this ticket

*Dual mellanox Snake test*
- [x] Deploy KVM system on a dual mellanox m2.xlarge Packet system
- [x] Setup VPP vSwitch similar to K8s worker node
- [x] Deploy VNFs to KVM in snake test cases:
  - [x] KVM Mellanox Snake (VSC)
      - [x] 3 Chains, 1 NF
      - [x] 3 Chains, 2 NFs
      - [x] 2 Chains, 3 NFs
- [x] Collect results and save logs to this ticket
- [x] Summarize results, including a single throughput number
- [ ] Add system resource information, including memory and cpu usage by VNFs and KVM to this ticket

**Comment by taylor** [comment]
*NFVbench results for VSC testing on Intel*
- 2 Chain 3 network functions: https://github.com/cncf/cnfs/blob/master/comparison/baseline_nf_performance-packet/results/4t2c_novlan/vsc_2c3n_18500000pps-1.log
- 3 Chain 2 network functions: https://github.com/cncf/cnfs/blob/master/comparison/baseline_nf_performance-packet/results/4t2c_novlan/vsc_3c2n_18500000pps-1.log

**Comment by michaelspedersen** [comment]
### Summary of "VSC KVM results using MLX (Packet.net)"
**Setup:** 
- 4t2c host VPP
- 1 RX queue per vHost (2 per VNF)
- m2.xlarge.x86 server.

**Test:**
- MRR (10Gbps)
- 60 second duration
- Single iteration

**Values in the matrix below are MPPS**
```
VMs, MLX (Packet.net), VSC
VSC   001   002   003   004   006
001   2.70* 2.56  1.89* 1.77  1.40
002   4.96  3.23  2.57  ----  ----
003   4.93* 3.18  ----  ----  ----
004   4.87  ----  ----  ----  ----
006   4.77  ----  ----  ----  ----
```
_(*) Indicates non-optimal (uneven) distribution of vHost queues in host VPP, which may impact performance._

**List of results (MPPS and Gbps):**
```
vnf_mlx_1c1n_10Gbps-1.log: 2,699,749 pps (1.8142 Gbps)
vnf_mlx_1c2n_10Gbps-1.log: 2,560,264 pps (1.7205 Gbps)
vnf_mlx_1c3n_10Gbps-1.log: 1,887,053 pps (1.2681 Gbps)
vnf_mlx_1c4n_10Gbps-1.log: 1,771,559 pps (1.1905 Gbps)
vnf_mlx_1c6n_10Gbps-1.log: 1,399,602 pps (940.5337 Mbps)
vnf_mlx_2c1n_10Gbps-1.log: 4,964,925 pps (3.3364 Gbps)
vnf_mlx_2c2n_10Gbps-1.log: 3,230,608 pps (2.1710 Gbps)
vnf_mlx_2c3n_10Gbps-1.log: 2,573,710 pps (1.7295 Gbps)
vnf_mlx_3c1n_10Gbps-1.log: 4,929,237 pps (3.3124 Gbps)
vnf_mlx_3c2n_10Gbps-1.log: 3,184,974 pps (2.1403 Gbps)
vnf_mlx_4c1n_10Gbps-1.log: 4,873,372 pps (3.2749 Gbps)
vnf_mlx_6c1n_10Gbps-1.log: 4,771,932 pps (3.2067 Gbps)
```
