### ISSUE TITLE
Create performance test for vDNS CNF equivalent to VNF test

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#26]
Goal: Testing Throughput, latency, resource util per unit of performance

Tasks:
---
- [x] Create vDNSgen container based on the VNF from #24 
- [x] Document network requirements and steps to create network for docker environment
- [x] Update host system as needed to support networking and test needs
   * [x] Document any host system requirements
- [x] Update vDNS CNF as needed to support networking/testing needs => #25 
- [x] Add support for specifying the rate for the DNS testing at runtime
- [x] Read packet counter via tap interface counter vs hardware counter
- [x] Pin cores used by countainer

**Comment by taylor** [comment]
The container pins the CPU cores used vs the VM test in #24
