### ISSUE TITLE
Create performance test for vBNG VNF

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#32]
Goal: Testing Throughput, latency, resource util per unit of performance

VMs:
- vBNG
- Packetgen
- (VXLan VM)  _may not be needed_

Tasks:
---
- [x] Investigate ability to do testing with Packetgen + vBNG w/o the need for vxlan.
   - [x] Remove vxlan as requirement in this issue if that is possible
   - [x] Update vBNG VM configuration to use needed network setup via ticket #31 
- [x] Create script to use Packetgen for testing vBNG VM 
- [x] Create top-level comaparison script for testing vBNG 
  - [x] create [vBNG_vm_test.sh ](https://github.com/cncf/cnfs/blob/master/comparison/box-by-box-kvm-docker/vBNG_vm_test.sh) to start VMs and run the test.  Eg.
      - Starts vBNG VM
      - Starts Packgen VM
      - Runs tests from packgen vm
   - [x] Test script with no VMs running

**Comment by michaelspedersen** [comment]
top-level script created with the following functionality:
`/vBNG_vm_test.sh`
- Update host network (VPP) with configuration needed for vBNG
- (_if necessary_) Create vBNG and Pktgen VMs
- Run benchmark
  - Low throughput by default (2002pps)
  - Higher throughput can be specified when running script
  - `./vBNG_vm_test.sh <rate>` (e.g. 10Kpps, 1Mpps)
- Remove vBNG and Pktgen VMs
  - `./vBNG_vm_test.sh clean`
