### ISSUE TITLE
Update vBNG to work in CSIT test environment

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#41]
In the new CSIT fd.io environment the vBNG setup needs to be adjusted.

There is some hardware specific configuration that needs to be set for the NF VPP configuration.

Also there are some issues with the Vagrant ubuntu box versions that we need to avoid (by setting specific versions to use).

- [x] (Container) Update vBNG VPP configuration
  - [x] Update dpdk whitelist with PCI devices `dev 0000:18:00.0 dev 0000:18:00.1`
  - [ ] Enable dpdk `no-multi-seg` setting
  - [x] Modify setup.gate configuration with correct interfaces and MAC addresses

- [x] (VM) Update vBNG VPP configuration [More details to be added]
  - [x] Modify Vagrantfile to use specific version of Ubuntu box
  - Newest version seems to have a problem with SSH
```
  config.vm.box = "generic/ubuntu1604"
  config.vm.box_version = "1.8.14"
```

**Comment by michaelspedersen** [comment]
Before running vBNG CNF, make sure NIC ports are bound to DPDK (vfio-pci):
```
# in testuser home directory (/home/testuser)
$ sudo ./dpdk-devbind.py -b vfio-pci 0000:18:00.0 0000:18:00.1
```
