### ISSUE TITLE
vBNG Results (CNF/VNF) on CSIT Testbench

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnfs#43]
- [ ] Add configuration notes
  - [ ] Host (system under test)
  - [ ] CNF
  - [ ] VNF
  - [ ] Pktgen
- [ ] Add Results
  - [ ] CNF (Throughput, Memory usage)
  - [x] VNF (Throughput, Memory usage)

**Comment by michaelspedersen** [comment]
### Results
Throughput has been measured as PDR (0.1%) and NDR (0.001%), which limits the number of dropped packets in the benchmark.

An issue has been observed with CNF throughput, as NDR is very low compared to other results.

## CNF
Throughput (5 iterations, PDR):
  - (1) 24,762,834 pps (16.6406 Gbps)
  - (1) 24,850,026 pps (16.6992 Gbps)
  - (1) 24,762,834 pps (16.6406 Gbps)
  - (1) 24,762,834 pps (16.6406 Gbps)
  - (1) 24,762,834 pps (16.6406 Gbps)
  - **PDR Average: 24,780,272 pps (16.65232 Gbps)**

Throughput (5 iterations, NDR):
  - (1) 332.0312 pps (494,094 Mbps)
  - (1) 332.0312 pps (494,094 Mbps)
  - (1) 332.0312 pps (494,094 Mbps)
  - (1) 332.0312 pps (494,094 Mbps)
  - (1) 332.0312 pps (494,094 Mbps)
  - **PDR Average: 332.0312 pps (494,094 Mbps)**

Memory (RSS)
  - **22.44 MB**

## VNF
Throughput (5 iterations, PDR):
  - (1) 24,966,284 pps (16.7773 Gbps)
  - (2) 24,995,348 pps (16.7969 Gbps)
  - (3) 24,850,026 pps (16.6992 Gbps)
  - (4) 24,908,156 pps (16.7383 Gbps) 
  - (5) 24,879,092 pps (16.7188 Gbps)
  - **PDR Average: 24,919,781 pps (16.7461 Gbps)**

Throughput (5 iterations, NDR)
  - (1) 24,791,898 pps (16.6602 Gbps)
  - (2) 24,879,092 pps (16.7188 Gbps)
  - (3) 24,791,898 pps (16.6602 Gbps)
  - (4) 24,820,962 pps (16.6797 Gbps)
  - (5) 24,762,834 pps (16.6406 Gbps)
  - **NDR Average: 24,809,337 pps (16.6719 Gbps)**

Memory (RSS)
  - **66.19 MB**

**Comment by lixuna** [comment]
closing
