### ISSUE TITLE
Deploy a 3-node Kolla OpenStack environment 

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#45]
Need: 3-node Kolla OpenStack environment deployed to Packet.net

Initial tasks:
---
- [x] Grant access to Packet.net project to Kumulus and rest of CNF dev team
- [x] Research using Kolla for deployment of 3 node dev cluster
- [x] Deploy and setup 3-node kolla openstack cluster on Packet.net
- [x] Share credential for access to OpenStack with CNF dev team
- [x] List components running on OpenStack cluster for each machine

Testing:
----
- [x] Access OpenStack controller node via SSH
- [x] Access OpenStack via admin credentials
- [x] Test cli access to openstack API from control node using admin creds
- [x] Test instantiating a VM w/no public internet IP
   - [x] Test accessing the VM from the controller
- [x] Test instantiating a VM w/a public internet IP
   - [x] Test accessing the VM from the controller
   - [x] Test accessing the VM from the internet

**Comment by lixuna** [comment]
09-02-2018 Update:

- I'm ready to launch a Kolla based OpenStack service into the empty project space as soon as you let me know that I can.

**Comment by lixuna** [comment]
@robertstarmer please ping me if I can help answer any questions re: the Kolla-based OpenStack service. Thanks for your help!

**Comment by lixuna** [comment]
09-17-2018 update: 
 
Initial system is up and running on three type-0 small instances. Still need to add a public network segment (floating IP addresses), and add other base service defaults (flavors, vm images, etc.).

API/Horizon is on http://147.75.108.179
User/password on the private channel.

**Comment by lixuna** [comment]
9-18-2018 update: 

A Cirros VM is also running, and is available via a public IP address at 147.75.71.119, standard cirros username and password.

**Comment by lixuna** [comment]
@denverwilliams please review the three type-0 small instances

**Comment by robertstarmer** [comment]
@taylor the following are the services:

## Control node
```horizon
heat_engine
heat_api_cfn
heat_api
neutron_metadata_agent
neutron_l3_agent
neutron_dhcp_agent
neutron_linuxbridge_agent
neutron_server
nova_novncproxy
nova_consoleauth
nova_conductor
nova_scheduler
nova_api
placement_api
glance_api
keystone_fernet
keystone_ssh
keystone
rabbitmq
mariadb
memcached
chrony
cron
kolla_toolbox
fluentd```

## Compute Node (duplicate on both machines)
```neutron_linuxbridge_agent
nova_compute
nova_libvirt
nova_ssh
chrony
cron
kolla_toolbox
fluentd```

**Comment by denverwilliams** [comment]
Steps to get Openstack API auth file - for api access.
1. Log into Horizon using the provided credentials http://147.75.108.179/project/api_access/
2. Select download "Openstack RC File v3"

**Comment by denverwilliams** [comment]
Set to test Openstack API access:
1. Source the above file ```source admin-openrc.sh```
2. Exec into docker container with the necessary openstack cli tools 
```docker run -ti --env-file <(env | grep OS_) quay.io/rackspace/openstack-cli /bin/sh```
3. List Services
```
$ openstack service list
+----------------------------------+-------------+----------------+
| ID                               | Name        | Type           |
+----------------------------------+-------------+----------------+
| 1885d54a233f4ff584a7e6cc6856800e | heat-cfn    | cloudformation |
| 4db31572e5a84c69ada68f04e94d0f27 | neutron     | network        |
| 7265cf7717b24bc49ba1d4e9981791a9 | placement   | placement      |
| 74e34fd362584f7a847479e9ac15eda0 | glance      | image          |
| 9ce09a59b28b4a4d99bf8e1629cfab4a | keystone    | identity       |
| accac9621d0541c0a657a763b4bb3899 | heat        | orchestration  |
| afa3cb097dfa44eaae582056c471b7fd | nova_legacy | compute_legacy |
| bc89a58c4879403e9fc8761e4d39ca14 | nova        | compute        |
+----------------------------------+-------------+----------------+
```

4. List compute nodes
```
 $ openstack hypervisor list
+----+---------------------+-----------------+---------------+-------+
| ID | Hypervisor Hostname | Hypervisor Type | Host IP       | State |
+----+---------------------+-----------------+---------------+-------+
|  1 | compute1.local.lan  | QEMU            | 147.75.89.231 | up    |
|  2 | compute2.local.lan  | QEMU            | 147.75.89.229 | up    |
+----+---------------------+-----------------+---------------+-------+
```
5. List VMs
``` 
 $ openstack server list
+--------------------------------------+--------+--------+---------------------------------------+--------------------------+----------+
| ID                                   | Name   | Status | Networks                              | Image                    | Flavor   |
+--------------------------------------+--------+--------+---------------------------------------+--------------------------+----------+
| 687d7dfc-e0f8-4dee-a9f3-3eb137d79d84 | test-2 | ACTIVE | private=192.168.100.8                 | cirros-0.3.5-x86_64-disk | m1.small |
| 78b14850-aacb-4f16-a6b3-19c047546b75 | test-3 | ACTIVE | private=192.168.100.16                | cirros-0.3.5-x86_64-disk | m1.small |
| f44f0733-18ec-4bac-885c-ca6cf06310a1 | test-1 | ACTIVE | private=192.168.100.12, 147.75.71.114 | cirros-0.3.5-x86_64-disk | m1.small |
| 39bdf7d4-fea7-4758-820f-59cfed2781da | test   | ACTIVE | private=192.168.100.3, 147.75.71.119  | cirros-0.3.5-x86_64-disk | m1.small |
+--------------------------------------+--------+--------+---------------------------------------+--------------------------+----------+
```
