### ISSUE TITLE
Grant Access to Kolla-based OpenStack environment to Vulk

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#46]
Please let me know who to pass the admin password on to. Or discover by logging in to the control node (default user is root, host is 147.75.108.179).  OpenStack admin password is available as:

```
grep keystone_admin /etc/kolla/passwords.yml
```

**Comment by lixuna** [comment]
@denverwilliams please review the three type-0 small instances and Cirros VM

**Comment by denverwilliams** [comment]
@lixuna i don't have ssh access @taylor will have to add my ssh keys. For the mean time i'll try get api access using horizon.

**Comment by robertstarmer** [comment]
@denverwilliams I've added the public key from your github.keys path.

**Comment by denverwilliams** [comment]
@robertstarmer awesome thanks.

**Comment by denverwilliams** [comment]
@lixuna 
SSH is working and Openstack passwords are available on the host.
```
owner@mx1:~
$ ssh root@147.75.108.179
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-134-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Thu Sep 27 00:16:31 2018 from 115.189.135.125
root@control:~# grep keystone_admin /etc/kolla/passwords.yml
keystone_admin_password: *******
```
