### ISSUE TITLE
Investigate SUSE bare metal deployment of OpenStack (Crowbar) to see if the result is vanilla OpenStack

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#47]
Request: Investigate SUSE bare metal deployment of OpenStack (Crowbar) to see if the result is vanilla OpenStack

Timebox: 2-3 hours for initial investigation

To determine: Will the crowbar path work to deploy OpenStack on Packet (MVP)?

- [ ]   if yes, estimate for time to deliver solution

- [ ]   if yes, documentation on how it works
  - [ ]   Documentation of the chosen bare metal approach with copy and pasteable, step-by-step, command line instructions similar to  https://kubernetes.io/docs/setup/minikube/#quickstart

- [x]   if no, documentation on why it won't work and the next approach to try

Chosen solution should:

- [x]  Use an open source license
- [x]  Support deployments completely from the command line
- [x]  Install vanilla OpenStack on bare metal 
- [x]  Not use Kubernetes to install OpenStack
- [x]  Not use specialized Web UI deployments of OpenStack onto Packet.net

**Comment by lixuna** [comment]
Good day, @robertstarmer 

I'm checking in to see how the investigation is coming along. Does it appear that the SUSE bare metal deployment of OpenStack (Crowbar) will be the appropriate solution to our goals?

**Comment by robertstarmer** [comment]
I'll be able to make a better determination this week, so far it does
appear that it _should_ be able to address the needs, but we're just in the
process of testing a deployment over the next two days. I'll have more data
as soon as it is either running, or we find a failure mode.

**Comment by lixuna** [comment]
Good day, @robertstarmer 

May we please have an update on the test deployment status?

**Comment by robertstarmer** [comment]
Hi @lixuna, yes, we've been able to deploy a 3 node test cluster using the Kitchen/Chef model, but we did this on VMs, and are now migrating that test to Packet and verifying that we can enable the right network functions in that environment. I should have a more complete answer later this evening.

**Comment by robertstarmer** [comment]
Alright, so we've verified that we can, in fact, use Chef to deploy to a controller+2x compute environment with chef.  There are still some manual processes (e.g. requesting and creating the initial nodes from packet, etc.) but we believe that there is either automation/scripts that will accomplish the requirements of launching nodes, or we can implement them fairly quickly.

Time estimate to implement/validate/document is 5 days.

**Comment by taylor** [comment]
@robertstarmer, sounds good for a 3-node dev cluster (comparable to the Kolla cluster).  We have provisioning code for requesting Packet.net machines which can be used with the openstack deployment code.

In the end we will want a "script" that someone runs from the command line to stand-up the entire cluster using only a Packet.net API key.

Rather than moving forward with the 3-node cluster I think we should hold off until next week so that you can take into consideration the full cluster setup we are needing for our network function use case.  I anticipate it to be at least a 5 node cluster setup.  More importantly will be the networking requirements between the nodes.

We'll be planning the rest of the requirements for the cluster (network, number of worker machines, etc) on Monday and will provide those details.  

/cc @lixuna

**Comment by robertstarmer** [comment]
@taylor That sounds good.  Please provide a pointer to the deploy code so that we can have a look at it, that'd be appreciated.  And once you have a model for your network requirements, we can make sure we can map them to the OS deployment.

**Comment by taylor** [comment]
@robertstarmer here is an example https://github.com/cncf/cnfs/tree/master/comparison/cnf_edge_throughput#quick-start-with-deployment-code

**Comment by robertstarmer** [comment]
It's based on the same Kitchen/Chef model that SUSE is based on,
specifically from https://github.com/openstack/openstack-chef

**Comment by lixuna** [comment]
Thank you @robertstarmer 

Initial investigation has been done, this ticket will be closed. 

The team has put together more implementation details for your review in https://github.com/cncf/cnfs/issues/93.
