### ISSUE TITLE
Test and review using Digital Rebar to deploy Kubernetes clusters on Packet.net

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#48]
Goal: Deploy a Kubernetes cluster to bare metal using a PXE boot install method on Packet.net

This should cover starting with no Packet nodes and all the way to a running Kubernetes cluster  which supports deploying apps via helm charts.

A user should be able to start with nothing more than a Packet.net account. 

The steps would look something like:
1. User has a Packet API key
2. User goes to a public github repo
3. User clones repo
4. User adds Packet API key to environment or some config file
5. User runs script or copy and pastes commands to get a k8s cluster

_Could start with SSH to a brand new packet instance, launched from Packet dashboard, and run everything else from command line_

**Comment by taylor** [comment]
Videos and docs referenced:

- RackN Rebar KRIB training/demo videos => https://www.youtube.com/playlist?list=PLXPBeIrpXjfhKqmTvxI5-0CmgUh82dztr
- Digital Rebar KRIB Complete Run Through => https://www.youtube.com/watch?v=rzBq3BsYQTM
- Using the RackN Terraform provider => https://www.youtube.com/watch?v=5trB3_IFFX8
- http://provision.readthedocs.io/en/tip/doc/content-packages/krib.html#component-krib
- https://provision.readthedocs.io/en/tip/doc/integrations/krib.html

**Comment by taylor** [comment]
Tried to use Terraform plan that builds the whole KRIB cluster from the command line following the video https://www.youtube.com/watch?v=5trB3_IFFX8 and documentation for building the terraform provider https://github.com/rackn/terraform-provider-drp#building-the-provider, but ran into validation errors.  Opened a ticket on the provider repo

https://github.com/rackn/terraform-provider-drp/issues/56

**Comment by taylor** [comment]
As there were no all command line walk-throughs for only using the rebar command  line we refocused on using the Rebar web ui for now.

**Comment by taylor** [comment]
TIP: Reset profile or create a new one to clear k8s API server IP

Reusing a existing profile fails because the Kubernetes API server IP is already populated in the profile

Creating a brand new profile or reseting the profile in rebar fixes the issue.

**Comment by taylor** [comment]
While using the web-ui we ran into what looks like a certificate related issue when the KRIB workflow is running.  Opened a upstream ticket, https://github.com/digitalrebar/provision-content/issues/133, with the instructions to reproduce.

**Comment by dankohn** [comment]
Cc @zehicle

**Comment by denverwilliams** [comment]
After to running the new steps below https://github.com/digitalrebar/provision-content/issues/133#issuecomment-418587494

- Go to https://portal.rackn.io/#/e/147.75.196.129:8092/bulk

- Select all machines to be used in new k8s cluster

- Use profile drop down to choose the profile "myprofile"

- Click the + symbol to add the profile to the machines

- Use Workflows drop down to choose the krib-reset-cluster workflow

- Click the Change Workflow button (play / skip button)   - _This will reset the certs_


We were successfully able to deploy a K8s cluster on RackN/Packet with both the GUI and Terraform

**Comment by zehicle** [comment]
@denverwilliams since this was successful, can we close the ticket?

**Comment by lixuna** [comment]
What's left: 
---

@denverwilliams to provide additional documentation to this ticket, then close.
