### ISSUE TITLE
Test and review using Digital Rebar to deploy OpenStack devstack on Packet.net

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#49]
Goal: Deploy a Kubernetes cluster to bare metal using a PXE boot install method on Packet.net

This should cover starting with no Packet nodes and all the way to a running single node devstack install of OpenStack

A user should be able to start with nothing more than a Packet.net account.

The steps would look something like:

1. User has a Packet API key
2. User goes to a public github repo
3. User clones repo
4. User adds Packet API key to environment or some config file
5. User runs script or copy and pastes commands to get a k8s cluster
6. Could start with SSH to a brand new packet instance, launched from Packet dashboard, and run everything else from command line

**Comment by taylor** [comment]
Failing to install devstack OpenStack content plugin because of a rebar upload error.  

Error: `STORE_ERROR: contents: dr-provision missing required feature  sprig`

Opened upstream ticket  https://github.com/digitalrebar/provision-content/issues/134

**Comment by lixuna** [comment]
What's left: 
---

@denverwilliams to provide additional documentation to this ticket
