### ISSUE TITLE
[Edge Throughput] Provision and install software for CNF Packet generator machine

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#51]
- [x] Provision a m2.xlarge.x86 machine on Packet.net for running the Trex packet generator for CNF testing
- [x] Setup SSH access for team
- [x] Install and configure NFVbench
- [x] Install and configure Trex and testing software to run directly on host
- [x] Document and make changes to OS and kernel as needed
  - [x] Example: Adding hugepage support https://github.com/cncf/cnfs/issues/42#issue-348889111

**Comment by taylor** [comment]
TBD: this may be combined with #50 to test from one system.
