### ISSUE TITLE
[Edge Throughput] Create terraform code to provision 4 physical Packet nodes with type m2.xlarge.x86

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#54]
Create terraform code to provision 4 physical Packet nodes with type m2.xlarge.x86 in an appropriate subfolder of https://github.com/cncf/cnfs/tree/master/comparison/cnf_edge_throughput

Tasks:
- [x] create terraform code to provision 4 physical packet nodes of type m2.xlarge.x86
- [x] Add steps to use terraform code in [readme](https://github.com/cncf/cnfs/blob/master/comparison/cnf_edge_throughput/README.md)

**Comment by denverwilliams** [comment]
Code added here https://github.com/cncf/cnfs/commit/895f5193751b6e373b58d9f53db6c187e54e7ec4

Steps can be found in the Readme https://github.com/cncf/cnfs/commit/3b28ff95cf16340bf83bdf3c40b6f0225bb83fee
