### ISSUE TITLE
[Edge Throughput] Setup VPP vSwitch for CNF machine

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#60]
- [x] Setup dpdk and host networking requirements
- [x] Enable VF trust in host (See #61)
- [x] Setup VPP startup.conf 
  - [x] enable and setup DPDK
- [x] Setup VPP setup.gate for 
   - [x] vlan tagging
   - [x] dpdk interfaces
- [x] add additional tasks as needed to this ticket
- [x] update comparison docs
- [x] update setup scripts and steps
- [x] add configuration to [code base](https://github.com/cncf/cnfs/tree/master/comparison/cnf_edge_throughput)

**Comment by michaelspedersen** [comment]
Functionality added in recent commit - Documentation (README.md) still needs to be updated
