### ISSUE TITLE
[Edge Throughput] Add code to provision layer 2 networking in Linux host for Packet.net

### ISSUE THREAD

**Issue by taylor** [cncf/cnfs#67]
Goal: Provide Layer 2 network setup needed for Edge Throughput comparison via code (eg. terraform + ansible)

Handle the following items:
- [x]  Manually set up hybrid networking via packet.net web ui
- [x] Leave bond0 alone on host / Packet configuration 
- [x] Remove bond for 2nd interface in host.  Eg. `echo "-enp94s0f1" > /sys/class/net/bond0/bonding/slaves`

- [x] Add additional tasks as needed to this ticket.

---

Test: 
- [x] provision 2 packet systems
- [x] both packet test systems should be in same L2 network
- [x] configure IP on layer 2 interface on each host
- [x] ping from one packet system to another
  - [x] No errors from ping
  - [x] No packet loss from ping
  - [x] All ping requests receive ping responses
- [x] arpping from one packet system to another
  - [x] No errors from arping
  - [x] All ARP requests receive ARP replies

**Comment by lixuna** [comment]
https://github.com/cncf/cnfs/blob/master/comparison/cnf_edge_throughput/README-layer2-network.md

**Comment by lixuna** [comment]
work was completed in #91 https://github.com/cncf/cnfs/commit/f883453a045bbf55696abf5304e0ec27c275f43c
