### ISSUE TITLE
Provide step-by-step CLI-only instructions for deploying k8s using rebar (KRIB)

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#71]
Goal: to provide Step-by-step instructions so that someone else can run the demo from the command line

Tasks:

- [ ] provide Step-by-step instructions to install, configure and use the Kubernetes content addon KRIB from the command line

- [ ] Include configuration of profiles, adding machines to the profile and correct workflow

**Comment by lixuna** [comment]
@denverwilliams Ready for peer review: 
---

- [ ] Please review: cut and paste script/docs for installing KRIB against an endpoint.  
https://github.com/digitalrebar/provision/blob/master/doc/integrations/krib.rst

- [ ] Please review: link to the compiled RST: https://provision.readthedocs.io/en/tip/doc/integrations/krib.html

**Comment by taylor** [comment]
Instructions for using KRIB, linked in the KRIB install doc, seem to be [KRIB content add-on docs](https://provision.readthedocs.io/en/tip/doc/content-packages/krib.html#component-krib)
