### ISSUE TITLE
Provide step-by-step CLI-only instructions to install and setup rebar

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#72]
Goal: to provide Step-by-step instructions to install and setup Digital Rebar from the command line

Tasks:

- [ ]  provide Step-by-step instructions to install and setup Digital Rebar from the command line

- [ ]  include configuring the subnet for DHCP, workflows, and any other required setup

**Comment by zehicle** [comment]
Please review: https://provision.readthedocs.io/en/tip/doc/quickstart.html

This has all the steps for install DRP on an existing system via the CLI.  DHCP is not needed for Packet.
