### ISSUE TITLE
Provide step-by-step CLI-only instructions for deploying OpenStack using Rebar (ROSE)

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#73]
Goal: to provide Step-by-step instructions to deploy OpenStack from the command line using Rebar 

Tasks:

- [ ] to provide Step-by-step instructions to deploy OpenStack from the command line

- [ ] include configuration details and correct workflow

Testing: 
- [ ] For the content add-on ROSE, I would expect to get a single node devstack deployed -- all from command line.

**Comment by zehicle** [comment]
Added in https://github.com/digitalrebar/provision-content/pull/143 
will show up in https://github.com/digitalrebar/provision-content/blob/master/rose/._Documentation.meta 

Please note that the :ref: links are NOT links, they are documentation cross references for the generated documentation.
