### ISSUE TITLE
Provide CLI steps for deploying the initial Packet server which is SSH accessible

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#74]
Goal: to provide copy-and-pastable step-by-step instructions for deploying the initial Packet server from the command line

Tasks:
- [ ] to provide copy-and-pastable step-by-step instructions for deploying the initial Packet server from the command line

- [ ] Specify OS requirements 

Testing: 

- [ ] Someone else should be able to SSH to the newly created Packet server

**Comment by zehicle** [comment]
It appears the best bet is to use Terraform for this: https://www.terraform.io/docs/providers/packet/ 

FWIW: if you install a DRP server with the Packet plugin, then you can use drpcli to create/destroy additional machines from a command line as per the DRP docs.
