### ISSUE TITLE
[CSIT Testbench] document hardware and software testing configuration

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#85]
Tasks: 

- [x]  Document hardware configuration for CSIT Testbench
- [x]  Document software configuration for CSIT Testbench
- [x]  Rename directory to CSIT CNF Verification Test
- [x]  Paste link to docs into this ticket

**Comment by taylor** [comment]
software in https://github.com/cncf/cnfs/tree/master/comparison/baseline_nf_performance
