### ISSUE TITLE
Summarize results for Chained NF Test Cases

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#89]
Gather, share and summarize results for Chained NF Test Cases

- [ ] Test Case 1: Containers connected directly with memif
- [ ]  Test Case 2: Containers connected through vpp with memif
- [ ] Test Case 3: VMs connected through vhost-user
- [ ] upload raw data into this ticket or a spreadsheet
- [ ] summarize performance comparisons

**Comment by taylor** [comment]
From the [nfvbench results log directory](https://github.com/cncf/cnfs/tree/master/comparison/baseline_nf_performance-csit/results/novlan) run:

```fgrep -R "|    Total    |" * | sort | awk -F '[ ]*[|][ ]*' '{print $1 " " $8 " (" $5 ")"}'```
