### ISSUE TITLE
Setup layer 2 networking using Packet API (from #67)

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#90]
Goal: Provide Layer 2 network setup needed for Edge Throughput comparison via code (eg. terraform + ansible)

Research/review:
- [x] Review and reference https://help.packet.net/article/58-layer-2-configurations
- [x] Research using terraform packet provider.  Note if it will work
- [x] Research using packet cli.  Note if it will work
- [x] Refer to https://github.com/cncf/cnfs/blob/master/comparison/cnf_edge_throughput/README-layer2-network.md
- [x] Follow steps starting with "Setup machine for the layer-2 network"

Add any research and preliminary testing to this ticket.

Add terraform and packet cli info to public ticket.  Summarize and add information for doing the setup to the public ticket.

Handle the following items:
- [x] Create a VLAN for a Packet.net project network
- [x] Enable layer 2 for an interface by removing the interface from bond
   * Equivalent web ui: Set machine in mixed-hybrid network via Packet API
- [x] Add VLAN(s) to an interface (eth1) via packet API

Add command line arguments for
- [x] create_vlan <description>
   *       print to stdout: VLAN ID (vxlan)
- [x]     debond_port <interface name> 
   *       print to stdout: success or failure
- [x]   assign_vlan <server name>
   *    print to stdout: success or failure

Integration with other Ansible provisioning code is in #113

DEFERRED:
- Delete VLAN via API
- Un-assign VLAN from interface on a machine

---

Testing with Packet.net API and web ui:
- [x] Verify HTTP return codes are successful
- [x] Verify from Packet web ui that the system network changes from layer-3 to mixed
- [x] Verify from Packet web ui that vlan is created
- [x] Verify from Packet web ui that vlan is assigned to port

Manually testing from hosts
Test: 
-  provision 2 packet systems or convert 2 back to default layer 3 in web ui
- both packet test systems should be in same L2 network
- configure IP on layer 2 interface on each host
-  ping from one packet system to another
  -  No errors from ping
  - No packet loss from ping
  - All ping requests receive ping responses
-  arpping from one packet system to another
  -  No errors from arping
  -  All ARP requests receive ARP replies

**Comment by taylor** [comment]
Everything working as expected
