### ISSUE TITLE
[CSIT] Create baseline configuration for Chained NFs Test Cases

### ISSUE THREAD

**Issue by michaelspedersen** [cncf/cnfs#92]
[CSIT] Create baseline configuration for Chained NFs Test Cases:

Tasks: 
- [x]  Test Case 1: Containers connected directly with memif
- [x]  Test Case 2: Containers connected through vpp with memif
- [x]  Test Case 3: VMs connected through vhost-user

New:
- [x] Support multiple single chains on a machine
- [x] Share results (in github repo)

**Comment by lixuna** [comment]
Update:  pmikus will be working on t22 action items in this GitHub issue, picking up where michaelspedersen left off

**Comment by taylor** [comment]
@pmikus let us know if we can help with this or other tickets as you are getting up to speed.

**Comment by pmikus** [comment]
@taylor Code wise I am good, I am continuing work after Michael. It was one of that, understand code and get oriented in multiple dir structures (cloned to each other). Run it, and get familiar with nfvbench. Initial results i do have. I am verifying results to align fully with our numbers.

**Comment by pmikus** [comment]
Regarding sharing the results, once approved that results are valid and comparable, i will be posting then where needed. Per our sync call.

**Comment by pmikus** [comment]
Initial set of baseline (single chain, single pipeline) results uploaded. Currently working on code changes to allow multiple chains to be deployed.

**Comment by pmikus** [comment]
Basic coding fully done. Baseline test results provided for single chains. Scripts can do provisioning of 8x8 chain matrix. I am working with Alec Hothan on managing nfvbench to work with multichains (few bugs spotted).
