### ISSUE TITLE
Review plans and diagrams for bare metal deployment of OpenStack

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#93]
----
Initial planning tasks:
- OpenStack installation software => Using Kitchen/Chef https://github.com/openstack/openstack-chef (See #47)
- [x] Initial planning of OpenStack cluster needs for Kubecon keynote CNF testing perspective
- [x] Writeup description and needs
- [x] Create diagrams for OpenStack cluster including network connections
- [x] Create slides with diagrams https://docs.google.com/presentation/d/1Z_Zel2GIfZ1of2Y67VTDecfQcIRxfavIpksvgYGs2us/edit#slide=id.g44fd9788f6_0_239

----

- [ ] @robertstarmer to review plans and diagrams
- [ ] Ask questions as needed
- [x] TBD: Schedule meeting to review plans and needs
- [ ] Add additional tasks needed for implementation

**Comment by taylor** [comment]
Cluster information and Q/A
---

## How many nodes OpenStack cluster?  What their high-level purposes? What other systems?
- 5 nodes total
- 2 controller nodes
- 3 compute nodes
   * Storage on compute nodes themselves
- 1 packet generator system on machine w/o OpenStack

## Hardware requirements
- Dataplane CNF Compute nodes (currently all 3) on system with Intel x710 4-port NICs
- Reserved system in Packet.net
- Packet.net machine type m2.xlarge.x86
- Intel 5120 Gold CPU


## Network configuration needs/request

Functionality:
- Required: External/public network access from all VMs (eg. downloads from internet work)
- Required: Host systems can access all VMs via SSH
- Required: Public internet SSH access to compute and control host systems
- Required: VMs on same host connect to each other over vhost through VPP vSwitch
- Nice to have: Inbound Public Internet connection to all VMs (eg. SSH)

Packet.net networks (created outside of OpenStack)
- Public internet (default Packet.net L3) connected to all openstack nodes and packet generator
- One Packet.net layer-2 (physical) networks connected to all systems used as OpenStack management network
- Two Packet.net layer-2 (physical) networks connected to all OpenStack machines and Packet generator system

OpenStack networks for Virtual Network Function dataplane traffic
- Two tenant networks connected to Packet.net layer-2 networks 
- VPP vSwitch on each compute node bridging the two Packet.net layer-2 networks
- VMs connected to VPP vSwitch over vhost

What network options do we have for the dataplane NFs
- *Preferred: VPP Neutron plugin* (eg. https://github.com/openstack/networking-vpp) 
   *  https://vtalks.net/talk/networking-vpp-a-fast-forwarding-vswitchvrouter-for-openstack/ 
   *  http://superuser.openstack.org/articles/vpp-vswitchvrouter-openstack/
- Risky/Unknown: VPP manually configured to work with OpenStack VMs/neutron
- _(NOT ACCEPTABLE)_ VMs connected to physical L2 network via public bridge on tap interfaces
  *  https://wiki.onap.org/display/DW/ONAP+vCPE+VPP-based+VNF+Installation+and+Usage+Information
   * Not good for performance
- SR-IOV to VMs (Virtual Functions mapped directly to VMs) 
   * https://docs.openstack.org/mitaka/networking-guide/config-sriov.html, 
   * https://docs.openstack.org/ocata/networking-guide/config-sriov.html, 
   * https://wiki.openstack.org/wiki/SR-IOV-Passthrough-For-Networking
   * Limited on number of Network Virtual Functions the network card supported
   * Chaining VNFs network connections will have limited configuration (eg. basic switching at NICs)

Deferred configuration needs
- CPU pinning
- NUMA configuration

**Comment by taylor** [comment]
![vnf testing openstack cluster for kubecon 2018 use case testing](https://user-images.githubusercontent.com/26697/46984312-2cd56380-d0aa-11e8-97a1-44c5cf4375ca.png)

![vnf testing openstack cluster for kubecon 2018 use case testing 1](https://user-images.githubusercontent.com/26697/46984324-32cb4480-d0aa-11e8-8566-bd4a2020c744.png)


![vnf testing openstack cluster for kubecon 2018 use case testing 2](https://user-images.githubusercontent.com/26697/46984330-39f25280-d0aa-11e8-98e4-32a94536468b.png)


![vnf testing openstack cluster for kubecon 2018 use case testing 3](https://user-images.githubusercontent.com/26697/46984335-3ced4300-d0aa-11e8-9177-bad777f6b43a.png)


![vnf testing openstack cluster for kubecon 2018 use case testing 4](https://user-images.githubusercontent.com/26697/46984339-3f4f9d00-d0aa-11e8-894c-310e7665b5cb.png)


![vnf testing openstack cluster for kubecon 2018 use case testing 5](https://user-images.githubusercontent.com/26697/46984342-424a8d80-d0aa-11e8-922b-73d109089fe5.png)

**Comment by taylor** [comment]
@robertstarmer ready for your review.

**Comment by robertstarmer** [comment]
@lixuna @taylor Reviewing.

**Comment by lixuna** [comment]
@robertstarmer checking in, please let us know if you would like to schedule a call to answers any questions you may have.

**Comment by lixuna** [comment]
Follow-up call scheduled for Tuesday, October 23.

**Comment by lixuna** [comment]
@robertstarmer please ping me and @taylor if we can review any documentation prior to the follow-up call.
