### ISSUE TITLE
Install/setup Intel NICs for KubeCon CNF testing in Packet.net m2.xlarge.x86 systems

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#94]
Goal: Acquire 9 NICS from Intel for KubeCon CNF testing on Packet.net

Tasks: 
---
- [x] start an new email thread to request 9 NICS from Intel
- [x] send shipping info
- [x] send model of card needs
- [x]  include Dell System type

- [x]  Send email to: 

- "Cahill, Francis"
- "Johnson, Brian" 
- "Ramakrishnan, Kuralamudhan"
- "Yoshinaka, Brian" 
- Lucina Stricko 
- Taylor Carpenter 
- Ed Warnicke 
- "Maciek Konstantynowicz (mkonstan)" 
- Zachary Smith 
- Michael Hsieh 
- Sam Machiz
- Dan Kohn
- King, Philip C 

--

### pcie NICs
- [x] NICs are sent from Intel to Packet
- [x] Packet validates that NICs are as expected
   * Did not work with server

### dual port NICs
- [x] Packet receives alternative NICs
   - enough for 5 of 9 servers
- [x] Packet validates that NICs are as expected
- [x] Packet installs alternative NICs to servers
- [x] Verification by CNF comparison team
   * [x] 4 ports show in host OS
  * SKIPPED - PCI slot and NUMA validation

### Quad port
- [x] Packet receives desired quad port NICs
- [x] Packet installs quad port NICs to servers
- [x] Packet verifies that NICs are working as expected
- [x] Verification by CNF comparison team
   * [x] 4 ports show in host OS
  * [ ]  - PCI slot and NUMA validation

**Comment by taylor** [comment]
## Packet.net system information for NF test machines

They are based on the Packet.net machine type: m2.xlarge.x86 -
 https://www.packet.com/cloud/servers/m2-xlarge/

This is based on Dell R640 - Intel Scalable - https://i.dell.com/sites/csdocuments/Shared-Content_data-Sheets_Documents/en/us/PowerEdge-R640-Technical-Guide.pdf

Details
- CPU: Dual Intel Xeon Gold 5120 2.2Ghz
- Memory: 384 GB of DDR4 ECC RAM
- Storage: 2 × 120 GB SSD, 3.2 TB of NVMe Flash 
- Network capability: 10Gbps w/ LACP

**Comment by taylor** [comment]
## NIC needs and information

- quad port card
- 10Gbps per port
- half-height or daughter card

First choice: https://www.dell.com/en-us/shop/dell-intel-x710-quad-port-10gb-da-sfp-network-daughter-card/apd/555-bckl/networking

An alternative is a PCIe card.  Ideally, we would need something like: https://ark.intel.com/products/83965/Intel-Ethernet-Converged-Network-Adapter-X710-DA4 
- The unit would need to be half height to fit in the Dell system

**Comment by lixuna** [comment]
10-24-2018 update: The wrong NICs were sent. Another set is being dispatched.

**Comment by taylor** [comment]
Because of issues putting the single quad port NIC into the Packet.net systems, the test systems have been outfitted with 2 dual port Intel X710 NICs.

5 systems have been setup with 2 x 2 port cards

NICs for the remaining 4 systems have been ordered.

Summary of PCI slot locations for 2 dual port Intel X710 NICs:

![image](https://user-images.githubusercontent.com/26697/47798268-0fcda100-dcf6-11e8-9090-4d88963227bb.png)

Detailed PCI device information:
![image](https://user-images.githubusercontent.com/26697/47798293-1a883600-dcf6-11e8-87ef-a0d8ce4e31f5.png)

**Comment by taylor** [comment]
Intel Quad port x710 NICs will be swapped into the systems today.

The daughter card (rNDC) versions of the quad port NICs arrived today and will be installed in the system rather than using the dual port NICs.

**Comment by taylor** [comment]
@pmikus, @mackonstan, @michaelspedersen 

Please review the pci slots used w/regards to NUMA and other considerations and add comments here.  Specifically if there are any issues or if the configuration is sufficient
