### ISSUE TITLE
Create helm charts for chained network function test case

### ISSUE THREAD

**Issue by lixuna** [cncf/cnfs#96]
convert Docker CNF to work on K8s

- [x] create base template and values files based on Docker code
- [x] Debug VPP failures dpdk start up
   * [x] Quick fix disable additional sockets in host to resolve NUMA zone
- [x] templating for cpu pinning
- [x] templating and config map for memif sockets
- [x] Implement alternative for NUMA zone isolation in the CNF

**Comment by denverwilliams** [comment]
@taylor @michaelspedersen 

After updating the helm templates to use the k8s "hugepage resource" to set available hugepages, vpp is aborting on start.
https://github.com/cncf/cnfs/commit/44d22603ca92f1ac7fdd34ba04c78edafcbdc261

```
dpdk_config:1275: EAL init args: -c 1 -n 4 --huge-dir /run/vpp/hugepages --file-prefix vpp --master-lcore 0 --socket-mem 64,64 
EAL: No free hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
DPDK physical memory layout:
Segment 0: IOVA:0x2cfac00000, len:8388608, virt:0x7fc45ba00000, socket_id:0, hugepage_sz:2097152, nchannel:0, nrank:0
Segment 1: IOVA:0x2cfb800000, len:58720256, virt:0x7fc455c00000, socket_id:0, hugepage_sz:2097152, nchannel:0, nrank:0
Segment 2: IOVA:0x5cfbc00000, len:67108864, virt:0x7fc44f600000, socket_id:1, hugepage_sz:2097152, nchannel:0, nrank:0
dpdk_pool_create:550: ioctl(VFIO_IOMMU_MAP_DMA) pool 'dpdk_mbuf_pool_socket0': Invalid argument (errno 22)
unix_physmem_region_alloc:172: physmem page for region 'dpdk_mbuf_pool_socket1' allocated on the wrong numa node (requested 1 actual 4294967294)
Aborted
```
